BLOOD_COLOR_NONE = -1

HITBOX_PLAYER_SPINE = 0
HITBOX_PLAYER_SPINE1 = 1
HITBOX_PLAYER_SPINE2 = 2
HITBOX_PLAYER_NECK = 3
HITBOX_PLAYER_L_CLAVICLE = 4
HITBOX_PLAYER_L_UPPERARM = 5
HITBOX_PLAYER_R_CLAVICLE = 6
HITBOX_PLAYER_R_UPPERARM = 7
HITBOX_PLAYER_L_FOREARM = 8
HITBOX_PLAYER_R_THIGH = 9
HITBOX_PLAYER_L_THIGH = 10
HITBOX_PLAYER_R_CALF = 11
HITBOX_PLAYER_R_FOOT = 12
HITBOX_PLAYER_R_TOE = 13
HITBOX_PLAYER_L_HAND = 14
HITBOX_PLAYER_R_FOREARM = 15
HITBOX_PLAYER_R_HAND = 16
HITBOX_PLAYER_L_CALF = 17
HITBOX_PLAYER_L_FOOT = 18
HITBOX_PLAYER_L_TOE = 19
HITBOX_PLAYER_HEAD = 20

HITBOX_ANTLION_GUARD_BODY = 0
HITBOX_ANTLION_GUARD_SPINE1 = 1
HITBOX_ANTLION_GUARD_SPINE2 = 2
HITBOX_ANTLION_GUARD_SPINE3 = 3
HITBOX_ANTLION_GUARD_HEAD = 4
HITBOX_ANTLION_GUARD_CLAW1_L = 5 -- front left leg - first seg
HITBOX_ANTLION_GUARD_CLAW2_L = 6 -- front left leg - 2nd seg
HITBOX_ANTLION_GUARD_CLAW3_L = 7 -- front left leg - 3rd seg
HITBOX_ANTLION_GUARD_CLAW1_R = 8 -- front right leg - first seg
HITBOX_ANTLION_GUARD_CLAW2_R = 9 -- front right leg - 2nd seg
HITBOX_ANTLION_GUARD_CLAW3_R = 10 -- front right leg - 3rd seg
HITBOX_ANTLION_GUARD_ARM_L = 11
HITBOX_ANTLION_GUARD_PELVIS = 12
HITBOX_ANTLION_GUARD_LEG1_L = 13
HITBOX_ANTLION_GUARD_LEG2_L = 14
HITBOX_ANTLION_GUARD_LEG1_R = 15
HITBOX_ANTLION_GUARD_LEG2_R = 16
HITBOX_ANTLION_GUARD_ARM_R = 17
HITBOX_ANTLION_GUARD_FINGER_R = 18
HITBOX_ANTLION_GUARD_FINGER_L = 19

HITBOX_ANTLION_BODY = 0
HITBOX_ANTLION_HEAD = 1
HITBOX_ANTLION_LEG_BKLF_SEG1 = 2
HITBOX_ANTLION_LEG_BKLF_SEG2 = 3
HITBOX_ANTLION_LEG_BKLF_SEG3 = 4
HITBOX_ANTLION_LEG_BKRT_SEG1 = 5
HITBOX_ANTLION_LEG_BKRT_SEG2 = 6
HITBOX_ANTLION_LEG_BKRT_SEG3 = 7
HITBOX_ANTLION_LEG_MID_L1 = 2
HITBOX_ANTLION_LEG_MID_L2 = 3
HITBOX_ANTLION_LEG_MID_L3 = 4
HITBOX_ANTLION_LEG_MID_R1 = 5
HITBOX_ANTLION_LEG_MID_R2 = 6
HITBOX_ANTLION_LEG_MID_R3 = 7
HITBOX_ANTLION_BACK = 8
HITBOX_ANTLION_LEG_FTRT_SEG1 = 9
HITBOX_ANTLION_LEG_FTRT_SEG2 = 10
HITBOX_ANTLION_LEG_FTRT_SEG3 = 11
HITBOX_ANTLION_LEG_FTLF_SEG1 = 12
HITBOX_ANTLION_LEG_FTLF_SEG2 = 13
HITBOX_ANTLION_LEG_FTLF_SEG3 = 14
HITBOX_ANTLION_LEG_R1 = 9
HITBOX_ANTLION_LEG_R2 = 10
HITBOX_ANTLION_LEG_R3 = 11
HITBOX_ANTLION_LEG_L1 = 12
HITBOX_ANTLION_LEG_L2 = 13
HITBOX_ANTLION_LEG_L3 = 14

/* This is what it would be, but valve screwed up.
HITBOX_ANTLION_LEG_L1 = 9
HITBOX_ANTLION_LEG_L2 = 10
HITBOX_ANTLION_LEG_L3 = 11
HITBOX_ANTLION_LEG_R1 = 12
HITBOX_ANTLION_LEG_R2 = 13
HITBOX_ANTLION_LEG_R3 = 14
*/



